### ISSUE TITLE
Advertisements_Database v1.5 Shortcomings

### ISSUE THREAD

**Issue by mrdiega** [johnoclockdk/cs2_Advertisements_Database#12]
```
css_plugins load Advertisements_Database
Loading plugin: AdvertisementsDatabase
Failed to load plugin /home/server2000cs2/steamcmd/server/game/csgo/addons/counterstrikesharp/plugins/Advertisements_Data occurred. (Unable to connect to any of the specified MySQL hosts.)
 ---> MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCoken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 449
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTin /_/src/MySqlConnector/Core/ConnectionPool.cs:line 410
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTin /_/src/MySqlConnector/Core/ConnectionPool.cs:line 415
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Int32 timeoutMn) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 105
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Int32 timeoutMn) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 135
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nulnnection.cs:line 929
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySq
   at Nexd.MySQL.MySqlDb.CreateContextAsync[T](Func`2 asyncContext)
   at Nexd.MySQL.MySqlDb.ExecuteNonQueryInternalAsync(String statement)
   at Nexd.MySQL.MySqlDb.ExecuteNonQueryAsync(String statement)
   --- End of inner exception stack trace ---
   at AdvertisementsDatabase.AdvertisementsDatabase.Load(Boolean hotReload) in C:\Users\john\Desktop\cs#\Advertisements_D
   at CounterStrikeSharp.API.Core.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterSt
   at CounterStrikeSharp.API.Core.GlobalContext.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterSt
   at CounterStrikeSharp.API.Core.GlobalContext.OnCSSPluginCommand(CCSPlayerController caller, CommandInfo info) in /homeobalContext.cs:line 260
 any of the specified MySQL hosts.)
 ---> MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 449
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 410
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 415
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 105
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 135
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 929
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 423
   at Nexd.MySQL.MySqlDb.CreateContextAsync[T](Func`2 asyncContext)
   at Nexd.MySQL.MySqlDb.ExecuteNonQueryInternalAsync(String statement)
   at Nexd.MySQL.MySqlDb.ExecuteNonQueryAsync(String statement)
   --- End of inner exception stack trace ---
   at AdvertisementsDatabase.AdvertisementsDatabase.Load(Boolean hotReload) in C:\Users\john\Desktop\cs#\Advertisements_Database\Advertisements_Database.cs:line 25
   at CounterStrikeSharp.API.Core.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/PluginContext.cs:line 108
   at CounterStrikeSharp.API.Core.GlobalContext.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 97
   at CounterStrikeSharp.API.Core.GlobalContext.OnCSSPluginCommand(CCSPlayerController caller, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 260
```
counterstrikesharp-build-54-linux-75fcf21
metamod 2.0 - build 1266

**Comment by johnoclockdk** [comment]
have you added you mysql info to config.cfg

**Comment by mrdiega** [comment]
> have you added you mysql info to config.cfg

For some reason the config was not created. I downloaded the latest version again today, and now the config has been created. But using the command `css_adv add "test" "chat"` the advertisement is not added to the database

**Comment by johnoclockdk** [comment]
the issue  is fix now and im close this thanks
